### ISSUE TITLE
only checking for gears at beginning/end. not at the middle of numbers

### ISSUE THREAD

**Issue by axsk** [pin2t/aoc2023#1]
Please help me understanding this.
In 
https://github.com/pin2t/aoc2023/blob/799ef4d3a02860744c30ebbf26056614fa0c9ccf/03.kts#L35C64-L35C64
you only check for the beginning and end, but what if a long number had a gear somewhere at the middle?

**Comment by pin2t** [comment]
Hi. Yes I agree this is valid concern. But in the input https://github.com/pin2t/aoc2023/blob/master/inputs/03.txt there are **not more** than 3-digits numbers. That is why it works for this specific input, but of course it is not general solution, I agree

**Comment by axsk** [comment]
oh right, gj then :)
